### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by tonymobster** [devcongress/slackbot#23]
We should probably setup testing and add tests for helpers and command handlers. Also [nock](https://github.com/node-nock/nock) and https://github.com/gratifychat/BotMock might be useful for mocking http calls and the slackbot respectively.

**Comment by tonymobster** [comment]
I couldn't for the life of me figure how to use BotMock though :(

**Comment by silentworks** [comment]
I have created a starting point pull request #36. I actually don't like what BotMock is doing, nor do I think it will be enough to test the API calls, I think until slack themselves or botkit provides something, I won't worry about integration tests too much.

**Comment by silentworks** [comment]
I think we have enough tests in the system now and have the facility to add new ones. I am referring to unit tests, not integration tests.
