### ISSUE TITLE
Add an upcoming events command and related jobs

### ISSUE THREAD

**Issue by tonymobster** [devcongress/slackbot#24]
The bot should be able to query the much hallowed event calendar for a list of upcoming events and should probably also post reminders to the group a day before and the morning of events. @yawboakye @claudey

**Comment by yawboakye** [comment]
@tonymobster I had this in mind but I just couldn't think it through properly. A couple of questions:
- where do the notification go? #events or #general?
- should the bot be allowed to use @channel or @here?

I'll go ahead and take a dig. We should have a PR for this by tomorrow.

**Comment by tonymobster** [comment]
I think the reminders should go to channel. A slack message with attachments indicating event name, time, venue and direct members to check #events for further details.

I think it should not use @channel or @here for now. That should be left to the discretion of admins.

**Comment by silentworks** [comment]
This task has been completed and merged in.
