### ISSUE TITLE
Consider teaching the bot NLP

### ISSUE THREAD

**Issue by tonymobster** [devcongress/slackbot#30]
The bot uses regexes and hardcoded strings to interpret messages received. Can we switch to NLP instead? There's wit.ai, api.ai, luis.ai and node libraries like natural that we could use.

This tutorial might also come in handy http://blog.templeton.host/self-training-nlp-enabled-slack-bot-tutorial/

**Comment by silentworks** [comment]
Yeah myself and @oddoye-david have been meaning to look into wit.ai for some time now, but just haven't got around to it. But if you want to kickstart the process by creating a PR, we will happily accept it. 💯

**Comment by tonymobster** [comment]
Lol ok. Currently looking into [api.ai](https://api.ai/), [Botkit integration](https://github.com/api-ai/api-ai-botkit) for this. The new wit.ai API is a bit confusing and not properly supported in Botkit.

**Comment by oddoye-david** [comment]
Motion for close

**Comment by tonymobster** [comment]
Seconded.
